/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    categories: Category;
    media: Media;
    products: Product;
    'review-requests': ReviewRequest;
    pages: Page;
    redirects: Redirect;
    'catalog-snapshots': CatalogSnapshot;
    releases: Release;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'review-requests': ReviewRequestsSelect<false> | ReviewRequestsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'catalog-snapshots': CatalogSnapshotsSelect<false> | CatalogSnapshotsSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  role: 'owner' | 'admin' | 'editor' | 'seo_reviewer' | 'media_manager' | 'publisher' | 'readonly';
  active: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  legacySourceId: number;
  nameVi: string;
  sourceName: string;
  slug: string;
  status: 'draft' | 'active' | 'archived';
  parent?: (string | null) | Category;
  sortOrder: number;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  path: string;
  storageKey: string;
  alt: string;
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  width: number;
  height: number;
  contentSha256: string;
  rightsStatus: 'pending' | 'cleared' | 'restricted' | 'expired';
  variants?:
    | {
        name: string;
        storageKey: string;
        width: number;
        height: number;
        contentSha256: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Khóa định danh nguồn, bất biến sau khi tạo.
   */
  legacySourceId: number;
  /**
   * Có thể trống hoặc trùng; tuyệt đối không dùng làm định danh.
   */
  sku?: string | null;
  nameVi: string;
  slugVi: string;
  descriptionVi?: string | null;
  specifications?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        sourceLine?: string | null;
        id?: string | null;
      }[]
    | null;
  packaging: {
    cells: {
      value?: string | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  attributes?:
    | {
        legacySourceId?: number | null;
        name: string;
        values: {
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  categories: (string | Category)[];
  media: (string | Media)[];
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * Dữ liệu nhập nguồn được bảo toàn để đối chiếu.
   */
  sourceMetadata: {
    sourceType: string;
    legacySlug: string;
    sourceName: string;
    legacyDescription?: string | null;
    sourceChecksum: string;
    canonicalSlugSha256: string;
    searchIndex?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    importedAt: string;
    legacyPublishedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-requests".
 */
export interface ReviewRequest {
  id: string;
  product: string | Product;
  requester: string | Admin;
  reviewer: string | Admin;
  comment: string;
  state: 'open' | 'resolved';
  resolvedAt?: string | null;
  resolvedBy?: (string | null) | Admin;
  resolution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  titleVi: string;
  slug: string;
  status: 'draft' | 'published' | 'archived';
  bodyVi?: string | null;
  seo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  fromPath: string;
  toPath: string;
  statusCode: '301' | '302' | '307' | '308';
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-snapshots".
 */
export interface CatalogSnapshot {
  id: string;
  snapshotId: string;
  schemaVersion: number;
  checksum: string;
  sourceChecksum: string;
  status: 'draft' | 'validated' | 'superseded';
  counts:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  importReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: string;
  name: string;
  status: 'draft' | 'ready' | 'released' | 'failed';
  catalogSnapshot: string | CatalogSnapshot;
  notes?: string | null;
  releasedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  eventType: string;
  actor: string | Admin;
  entityType: string;
  entityId: string;
  occurredAt: string;
  requestId?: string | null;
  ip?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'review-requests';
        value: string | ReviewRequest;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'catalog-snapshots';
        value: string | CatalogSnapshot;
      } | null)
    | ({
        relationTo: 'releases';
        value: string | Release;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admins';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  legacySourceId?: T;
  nameVi?: T;
  sourceName?: T;
  slug?: T;
  status?: T;
  parent?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  path?: T;
  storageKey?: T;
  alt?: T;
  metadata?: T;
  width?: T;
  height?: T;
  contentSha256?: T;
  rightsStatus?: T;
  variants?:
    | T
    | {
        name?: T;
        storageKey?: T;
        width?: T;
        height?: T;
        contentSha256?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  legacySourceId?: T;
  sku?: T;
  nameVi?: T;
  slugVi?: T;
  descriptionVi?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        sourceLine?: T;
        id?: T;
      };
  packaging?:
    | T
    | {
        cells?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  attributes?:
    | T
    | {
        legacySourceId?: T;
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  categories?: T;
  media?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  status?: T;
  publishedAt?: T;
  sourceMetadata?:
    | T
    | {
        sourceType?: T;
        legacySlug?: T;
        sourceName?: T;
        legacyDescription?: T;
        sourceChecksum?: T;
        canonicalSlugSha256?: T;
        searchIndex?: T;
        importedAt?: T;
        legacyPublishedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-requests_select".
 */
export interface ReviewRequestsSelect<T extends boolean = true> {
  product?: T;
  requester?: T;
  reviewer?: T;
  comment?: T;
  state?: T;
  resolvedAt?: T;
  resolvedBy?: T;
  resolution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titleVi?: T;
  slug?: T;
  status?: T;
  bodyVi?: T;
  seo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-snapshots_select".
 */
export interface CatalogSnapshotsSelect<T extends boolean = true> {
  snapshotId?: T;
  schemaVersion?: T;
  checksum?: T;
  sourceChecksum?: T;
  status?: T;
  counts?: T;
  importReport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  catalogSnapshot?: T;
  notes?: T;
  releasedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  eventType?: T;
  actor?: T;
  entityType?: T;
  entityId?: T;
  occurredAt?: T;
  requestId?: T;
  ip?: T;
  before?: T;
  after?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}