#!/usr/bin/env python3
"""Translate product names EN->VI (rule-based, full-vocab phrase dictionary).
Sinh data/products_vi.json: {id, sku, name_en, name_vi, slug_vi}"""
import json, os, re, html as H, unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')

# ---------- TỪ ĐIỂN CỤM (được sort theo độ dài giảm dần lúc chạy) ----------
T = [
# --- cụm sản phẩm dài ---
("ROLLER CABINET TOOLS SET","tủ dụng cụ bánh xe"),
("ROLLER CABINET TOOL SET","tủ dụng cụ bánh xe"),
("ROLLING TOOL CART","xe đẩy dụng cụ có bánh"),
("TOOL CHEST SET","bộ rương dụng cụ"),
("TOOL CHEST","rương dụng cụ"),
("HOUSEHOLD TOOL SET","bộ dụng cụ gia đình"),
("HOME TOOL KIT","bộ đồ nghề gia đình"),
("TOOL KIT","bộ đồ nghề"),
("TOOLS SET","bộ dụng cụ"),
("TOOL SET","bộ dụng cụ"),
("TOOL SETS","bộ dụng cụ"),
("SOCKET SET","bộ tuýp"),
("SOCKETS SET","bộ tuýp"),
("SOCKET RAIL","thanh gắn tuýp"),
("IMPACT SOCKET SET","bộ tuýp động lực"),
("DEEP IMPACT SOCKET SET","bộ tuýp sâu động lực"),
("DEEP SOCKET SET","bộ tuýp sâu"),
("NUT SOCKET SET","bộ tuýp đai ốc"),
("SPARK PLUG SOCKET","tuýp bugi"),
("DRIVE SOCKET SET","bộ tuýp"),
("DRIVE SOCKET","đầu tuýp"),
("DEEP SOCKET","đầu tuýp sâu"),
("IMPACT SOCKET","đầu tuýp động lực"),
("SOCKET","đầu tuýp"),
("SCREWDRIVER BIT SET","bộ mũi vít"),
("IMPACT SCREWDRIVER BIT SET","bộ mũi vít động lực"),
("BIT SET","bộ mũi vít"),
("BIT HOLDER","ổ cắm mũi vít"),
("MAGNETIC BIT HOLDER SET","bộ ổ cắm mũi vít nam châm"),
("SCREWDRIVER SET","bộ tua vít"),
("SCREWDRIVERS SET","bộ tua vít"),
("GO THROUGH SCREWDRIVER","tua vít xuyên"),
("SCREWDRIVER","tua vít"),
("SCREWDRIVERS","tua vít"),
("CHANGEABLE SCREWDRIVER SET","bộ tua vít đổi mũi"),
("COMBINATION SPANNER","cờ lè kết hợp"),
("COMBINATION SPANNERS","cờ lè kết hợp"),
("COMBINATION WRENCH","cờ lè kết hợp"),
("ADJUSTABLE WRENCH","cờ lè rút ruột"),
("TORQUE WRENCH","cờ lè lực"),
("PIPE WRENCH","cờ lè ống nước"),
("STRAP WRENCH","cờ lè dây"),
("OIL FILTER MASTER PLIERS","kìm tháo lọc dầu"),
("OIL FILTER WRENCH","cờ lè mở lọc dầu"),
("IMPACT WRENCH","súng siết bu lông"),
("ANGLE IMPACT WRENCH","súng siết bu lông góc"),
("SPANNER SET","bộ cờ lè"),
("SPANNER","cờ lè"),
("WRENCH","cờ lè"),
("RATCHET HANDLE","tay quay cờ lè ráy"),
("REVERSIBLE RATCHET","cờ lè ráy đảo chiều"),
("QUICK RELEASE RATCHET","cờ lè ráy tháo nhanh"),
("RATCHET","cờ lè ráy"),
("EXTENSION BAR","thanh nối dài"),
("SLIDING T BAR","cần chữ T trượt"),
("SLIDING T-BAR","cần chữ T trượt"),
("UNIVERSAL JOINT","khớp các đăng"),
("BREAKER BAR","cần đột lực"),
("SOCKET ADAPTOR","đầu chuyển tuýp"),
("SOCKET ADAPTER","đầu chuyển tuýp"),
("BIT ADAPTOR","đầu chuyển mũi vít"),
("ADAPTATOR","đầu chuyển"),
("ADAPTER","đầu chuyển"),
("ADAPTOR","đầu chuyển"),
# kìm
("WATER PUMP PLIERS","kìm bơm nước"),
("COMBINATION PLIERS","kìm điện"),
("DIAGONAL CUTTING PLIERS","kìm cắt ngang"),
("LONG NOSE PLIERS","kìm mũi nhọn dài"),
("BENT NOSE PLIERS","kìm mũi cong"),
("INTERNAL CIRCLIP PLIER","kìm chẻ vòng bi trong"),
("EXTERNAL CIRCLIP PLIER","kìm chẻ vòng bi ngoài"),
("CIRCLIP PLIERS","kìm chẻ vòng bi"),
("LOCKING PLIERS","kìm kẹp khóa"),
("CHAIN CLAMP LOCKING PLIERS","kìm kẹp khóa kiểu xích"),
("SHEET METAL CLAMP","kìm kẹp tôn"),
("WELDING CLAMP","kìm kẹp hàn"),
("MINI PLIERS","kìm mini"),
("FUEL LINE PLIERS","kìm dây nhiên liệu"),
("FUEL LINE kìmS","kìm dây nhiên liệu"),
("MASTER PLIERS","kìm đa năng"),
("CRIMPING PLIERS","kìm ép đầu cos"),
("CRIMPING TOOL","kìm ép đầu cos"),
("STRIPPING PLIERS","kìm tuốt dây"),
("WIRE STRIPPING PLIERS","kìm tuốt dây"),
("CABLE CUTTING PLIER","kìm cắt cáp"),
("PRUNING SHEARS","kéo cắt tỉa cây"),
("AVIATION SNIPS","kéo cắt tôn"),
("TIN SNIPS","kéo cắt tôn mỏng"),
("TINMAN'S SNIPS","kéo cắt tôn thợ thiếc"),
("SNIPS","kéo cắt tôn"),
("SCISSORS","kéo"),
("KITCHEN SCISSORS","kéo nhà bếp"),
("PINCERS","kìm nhổ đinh"),
("PINCE","kìm nhổ đinh"),
("PLIER","kìm"),
("PLIERS","kìm"),
("PLITERS","kìm"),
# búa - đục - dũa
("BALL PEIN HAMMER","búa tròn"),
("MACHINIST HAMMER","búa cơ khí"),
("CLAW HAMMER","búa nứa"),
("RIP HAMMER","búa nứa"),
("SLEDGE HAMMER","búa lớn"),
("STONING HAMMER","búa đá"),
("DEAD BLOW MALLET","búa cao su giảm nảy"),
("RUBBER MALLET","búa cao su"),
("HAMMER","búa"),
("MALLET","búa gỗ"),
("HATCHET","rìu nhỏ"),
("HAND AXE","rìu cầm tay"),
("ADZE","rìu bóc gỗ"),
("COLD CHISEL","đục sắt"),
("CENTER PUNCH","mũi tâm"),
("CENTRE PUNCH","mũi tâm"),
("PUNCH SET","bộ mũi tâm"),
("PUNCH","mũi đục"),
("STEEL FILES","dũa sắt"),
("STEEL FILE","dũa sắt"),
("FILE SET","bộ dũa"),
("FILES","bộ dũa"),
("FILE","dũa"),
("SHARPENING STONES","đá mài sắc"),
("NUT SPLITTER SET","bộ dụng cụ tách đai ốc"),
("NUT SPLITTER","dụng cụ tách đai ốc"),
("SCRAPER","dao nạo"),
("PUTTY KNIFE","dao trét bả"),
("CROWBAR","còng sắt (giá nhổ đinh)"),
("WRECKING BAR","còng sắt"),
# cưa
("HACKSAW FRAME","khung cưa sắt"),
("HACKSAW","cưa sắt"),
("HANDSAW","cưa tay"),
("RECIPROCATING SAW","máy cưa kiếm"),
("JIGSAW","máy cưa lọng"),
("JIG SAW","máy cưa lọng"),
("MITER SAW","máy cưa góc"),
("MITRE SAW","máy cưa góc"),
("CIRCULAR SAW","máy cưa đĩa"),
("TABLE SAW","máy cưa đĩa bàn"),
("BAND SAW","máy cưa băng"),
("CHAINSAW","máy cưa xích"),
("CHAIN SAW","máy cưa xích"),
("ALLOY SAW BLADE","lưỡi cưa đĩa hợp kim"),
("SAW BLADE","lưỡi cưa"),
("SAW","cưa"),
("MULTI TOOL BLADE SET","bộ lưỡi máy đa năng"),
("OSCILLATING MULTI TOOL","máy đa năng rung"),
("MULTI TOOL","máy đa năng"),
# đo lường
("TAPE MEASURE","thước dây"),
("MEASURING TAPE","thước dây"),
("STEEL RULE","thước thép"),
("SPIRIT LEVEL","thước thủy"),
("TRY SQUARE","thước vuông ê ke"),
("LASER LEVEL","máy cân bằng laser"),
("CALIPER","panh me"),
("DIGITAL CALIPER","panh me điện tử"),
("MICROMETER","panme"),
("VERNIER","có nón noni"),
("FEELER GAUGE","thước lá đo khe hở"),
("GAUGES","thước đo"),
("GAUGE","thước đo"),
("DISTANCE METER","máy đo khoảng cách"),
("LASER DISTANCE METER","máy đo khoảng cách laser"),
("INFRARED THERMOMETER","nhiệt kế hồng ngoại"),
("MULTIMETER","đồng hồ vạn năng"),
("VOLTAGE TESTER","bút thử điện"),
("TESTER","bút thử"),
("COMPASS","compa"),
("MARKING GAUGE","thước kẻ vạch"),
("CARPENTER PENCIL","bút chì mộc"),
("MARKER","bút dạ"),
# điện - điện tử
("CABLE KNIFE","dao cắt cáp"),
("DISMANTLING KNIFE","dao tháo vỏ cáp"),
("ELECTRICIAN'S KNIFE","dao thợ điện"),
("ELECTRICIAN KNIFE","dao thợ điện"),
("UTILITY KNIFE","dao rọc giấy"),
("SNAP OFF KNIFE","dao rọc giấy lưỡi bẻ"),
("SNAP-OFF KNIFE","dao rọc giấy lưỡi bẻ"),
("KNIFE","dao"),
("SOLDERING IRON","mỏ hàn thiếc"),
("SOLDER","hàn thiếc"),
("WIRE BRUSH","bàn chải sắt"),
("CUP TWIST WIRE BRUSH","bàn chải sắt dạng cốc"),
("BRUSH","bàn chải"),
("CRIMPING","ép đầu cos"),
("WIRE","dây"),
("CABLE","cáp"),
("TEST LEADS","dây dẫn thử"),
# máy dụng cụ điện / pin
("ANGLE GRINDER","máy mài góc"),
("BENCH GRINDER","máy mài bàn"),
("DIE GRINDER","máy mài thẳng đầu nhỏ"),
("GRINDER","máy mài"),
("HAMMER DRILL","máy khoan động lực"),
("IMPACT DRILL","máy khoan động lực"),
("CORDLESS DRILL","máy khoan dùng pin"),
("ELECTRIC DRILL","máy khoan điện"),
("HAND DRILL","máy khoan cầm tay"),
("DRILL","máy khoan"),
("DEMOLITION HAMMER","máy đục bê tông"),
("ROTARY HAMMER","máy khoan bê tông"),
("IMPACT DRIVER","súng bắn vít"),
("SCREW DRIVER MACHINE","máy vặn vít"),
("ELECTRIC SCREWDRIVER","máy vặn vít điện"),
("HEAT GUN","súng nhiệt"),
("GLUE GUN","súng bắn keo"),
("CAULKING GUN","súng bắn keo trét"),
("GREASE GUN","súng bơm mỡ"),
("SPRAY GUN","súng phun sơn"),
("AIR SPRAY GUN","súng phun sơn khí"),
("HVLP SPRAY GUN","súng phun sơn HVLP"),
("AIRBRUSH","súng phun khí nhỏ"),
("SPRAY","phun"),
("ORBITAL SANDER","máy chà nhám rung"),
("RANDOM ORBITAL SANDER","máy chà nhám random"),
("BELT SANDER","máy chà nhám băng"),
("DRYWALL SANDER","máy chà nhám tường"),
("SANDER","máy chà nhám"),
("POLISHER","máy đánh bóng"),
("PLANER","máy bào"),
("ROUTER","máy phay"),
("VACUUM CLEANER","máy hút bụi"),
("VACUUM","hút bụi"),
("CLEANER","máy làm sạch"),
("BLOWER","máy thổi"),
("LEAF BLOWER","máy thổi lá"),
("AIR COMPRESSOR","máy nén khí"),
("COMPRESSOR","máy nén khí"),
("PRESSURE WASHER","máy rửa xe áp lực cao"),
("HIGH PRESSURE WASHER","máy rửa áp lực cao"),
("WASHING MACHINE","máy rửa"),
("GENERATOR","máy phát điện"),
("WELDING MACHINE","máy hàn"),
("WELDING INVERTER","máy hàn inverter"),
("INVERTER WELDER","máy hàn inverter"),
("WELDING","hàn"),
("INVERTER","inverter"),
("PLASMA CUTTER","máy cắt plasma"),
("MIG","MIG"),
("MMA","MMA"),
("ELECTRODE HOLDER","kìm giữ điện cực hàn"),
("EARTH CLAMP","kìm mát hàn"),
("FLASHLIGHT","đèn pin"),
("WORK LIGHT","đèn công trình"),
("WORKLIGHT","đèn công trình"),
("HEADLAMP","đèn đội đầu"),
("FLOOD LIGHT","đèn pha chiếu sáng"),
("LED LIGHT","đèn LED"),
("LAMP","đèn"),
("BATTERY PACK","pin dung nguồn"),
("BATTERY CHARGER","bộ sạc pin"),
("BATTERY","pin"),
("CHARGER","bộ sạc"),
("POWER TOOL ACCESSORIES","phụ kiện máy dụng cụ"),
# khí nén
("AIR TOOLS","dụng cụ khí nén"),
("AIR HOSE DRAIN VALVE","van xả nước đường khí"),
("AIR HOSE","dây hơi khí nén"),
("COUPLER","khớp nối nhanh"),
("CONNECTOR","đầu nối"),
("NAILER","súng bắn đinh"),
("NAIL GUN","súng bắn đinh"),
("STAPLER","súng bắn ghim"),
("STAPLE GUN","súng bắn ghim"),
("TACKER","súng bắn ghim"),
("RIVETER","kìm bấm đinh tán"),
("RIVET","đinh tán"),
("AIR RIVETER","súng bấm đinh tán khí"),
("FLARING TOOL","dụng cụ loe ống"),
("AIR CUT OFF TOOL","máy cắt khí nén"),
("SPRAYERS","bình phun"),
("BACKPACK SPRAYER","bình phun đeo lưng"),
("SPRAYER","bình phun"),
# ô tô - nâng hạ
("JACK STAND","chân con đội"),
("FLOOR JACK","con đội nằm"),
("HYDRAULIC BOTTLE JACK","con đội chai thủy lực"),
("HYDRAULIC JACK","con đội thủy lực"),
("TRANSMISSION JACK","con đội nâng hộp số"),
("ENGINE CRANE","sầm nâng động cơ"),
("ENGINE STAND","giá dựng động cơ"),
("MACPHERSON STRUT EXTRACTOR","dụng cụ tháo giảm xóc MacPherson"),
("COIL SPRING COMPRESSOR","dụng cụ nén lò xo giảm xóc"),
("BALL JOINT SEPARATOR","dụng cụ tách khớp cầu"),
("BEARING SEPARATOR","dụng cụ tách vòng bi"),
("GEAR PULLER","dụng cụ kéo bánh răng"),
("BEARING PULLER","dụng cụ kéo vòng bi"),
("PULLER","dụng cụ kéo"),
("SHOP PRESS","máy ép bàn thủy lực"),
("TIRE INFLATOR","máy bơm lốp"),
("TIRE REPAIR KIT","bộ vá lốp"),
("TIRE","lốp xe"),
("WHEEL BALANCER","máy cân bằng bánh xe"),
("VALVE SPRING COMPRESSOR","dụng cụ nén lò xo xupap"),
("BRAKE CALIPER WIND BACK TOOL","dụng cụ đẩy piston heo dầu phanh"),
("BRAKE BLEEDER","dụng cụ xả gió phanh"),
("FUEL INJECTION TEST","dụng cụ kiểm tra bơm kim phun"),
("OIL DRAIN PAN","chậu hứng dầu thải"),
("OIL CAN","vòi bôi dầu"),
("GREASE","mỡ bôi trơn"),
("CAR FUSE PULLER","kèm lấy rơ le ô tô"),
("WINDSHIELD CUTTER","dụng cụ cắt kính ô tô"),
("RADIATOR PRESSURE TESTER","dụng cụ test áp két nước"),
("SUCTION GUN","súng hút dầu"),
("AUTO REPAIR","sửa chữa ô tô"),
("CAR","ô tô"),
("TRUCK","xe tải"),
("MOTORCYCLE","xe máy"),
("BICYCLE","xe đạp"),
# xây dựng
("CONCRETE MIXER","máy trộn bê tông"),
("VIBRATORY ROLLER","lu rung"),
("PLATE COMPACTOR","máy đầm cóc"),
("TAMPING RAMMER","máy đầm nhảy"),
("CONCRETE VIBRATOR","máy rung bê tông"),
("POWER FLOATER","máy lái nền"),
("POWER TROWEL","máy lái nền"),
("CONCRETE SCREED","dầm rung san nền bê tông"),
("BARROW","cút kít"),
("DUMPER","xe ben mini"),
("PALLET TRUCK","xe nâng tay pallet"),
("STACKER","xe nâng xếp hàng"),
("HOIST","palang"),
("WINCH","tời quấn"),
("CHAIN BLOCK","palang xích kéo tay"),
("LIFTING SLINGS","dây cẩu"),
("LADDER","thang"),
("MULTIPURPOSE ALUMINIUM LADDER","thang nhôm đa năng"),
("MULTI PURPOSE ALUMINUM LADDER","thang nhôm đa năng"),
("ALUMINIUM LADDER","thang nhôm"),
("ALUMINUM LADDER","thang nhôm"),
("WORK PLATFORM","scaffold làm việc"),
("SCAFFOLD","giàn giáo"),
("HANDTRUCK","xe đẩy tay"),
("TROLLEY","xe đẩy"),
("CART","xe đẩy"),
("DOLLY","xe trượt hàng"),
("WORKBENCH","bàn làm việc"),
# làm vườn
("GRASS TRIMMER","máy cắt cỏ cầm tay"),
("BRUSH CUTTER","máy cắt cỏ"),
("HEDGE TRIMMER","máy cắt hàng rào"),
("LAWN MOWER","máy cắt cỏ đẩy"),
("CHAINSAW","máy cưa xích"),
("PRUNER","kéo cắt tỉa"),
("LOPPER","kìm cắt cành lớn"),
("LOPPING SHEAR","kéo cắt cành lớn"),
("TREE PRUNER","dụng cụ cắt cành cao"),
("FRUIT PICKER","dụng cụ hái trái cây"),
("SHRUB","cây cảnh"),
("SPRINKLER","vòi phun tưới"),
("SPRINKLERS","vòi phun tưới"),
("WATERING LANCE","cần tưới nước"),
("HOSE REEL TRUCK","xe cuộn dây tưới"),
("HOSE REEL","cuộn dây tưới"),
("HOSE CONNECTOR SET","bộ đầu nối ống tưới"),
("HOSE CONNECTOR","đầu nối ống tưới"),
("HOSE MENDER","đầu nối ống hở"),
("HOSE","ống dẫn nước"),
("TAP ADAPTOR","đầu chuyển vòi nước"),
("SHOVEL","xẻng"),
("SPADEFUL","xẻng"),
("HOE","cuốc"),
("MATTOCK","cuốc chim"),
("RAKE","cào"),
("GARDEN RAKE","cào làm vườn"),
("FORK","nĩa làm vườn"),
("TRANSPLANTER","dụng cụ trồng cây"),
("MACHETE","dao phát quang"),
("BROOM","chổi"),
("WHEELBARROW","xe cút kít"),
("TWEEZERS","cái nhíp"),
# PPE
("SAFETY HELMET","mũ bảo hộ"),
("HELMET","mũ bảo hộ"),
("SAFETY GOGGLES","kính bảo hộ"),
("GOGGLE","kính bảo hộ"),
("SAFETY GLASSES","kính bảo hộ"),
("GLASSES","kính"),
("FACE SHIELD","kính che mặt"),
("SAFETY SHOES","giày bảo hộ"),
("SAFETY BOOTS","giày bảo hộ"),
("BOOTS","giày bảo hộ"),
("WORKING GLOVES","găng tay làm việc"),
("WORK GLOVES","găng tay làm việc"),
("SAFETY GLOVES","găng tay bảo hộ"),
("NITRILE GLOVES","găng tay nitrile"),
("LATEX GLOVES","găng tay latex"),
("GLOVES","găng tay"),
("EAR MUFF","chụp tai chống ồn"),
("EARPLUG","nút tai chống ồn"),
("EAR PLUG","nút tai chống ồn"),
("MUFF","chụp tai"),
("DUST MASK","khẩu trang chống bụi"),
("FACE MASK","khẩu trang"),
("MASK","mặt nạ"),
("RESPIRATOR","mặt nạ phòng độc"),
("HALF FACEPIECE","mặt nạ nửa mặt"),
("WELDING MASK","mặt nạ hàn"),
("REFLECTIVE VEST","áo phản quang"),
("VEST","áo phản quang"),
("SAFETY HARNESS","đai an toàn toàn thân"),
("HARNESS","đai an toàn"),
("OVERALLS","quần áo bảo hộ"),
("WORKWEAR","quần áo bảo hộ"),
("RAINCOAT","áo mưa"),
("JACKET","áo khoác"),
("TROUSERS","quần bảo hộ"),
("SHIRT","áo bảo hộ"),
("SUSPENDERS","dây đeo quần"),
("WRIST SUPPORT","nẹp cổ tay"),
("KNEE PADS","đệm gối bảo hộ"),
("KNEE","gối"),
("FATIGUE MAT","thảm giảm chấn"),
("LANYARDS","dây an toàn treo"),
("STRAPS","dây đai"),
("STRAP","dây đai"),
("HELMETS","mũ bảo hộ"),
# phụ kiện cắt mài khoan
("CUTTING DISC","đĩa cắt"),
("GRINDING DISC","đĩa mài"),
("FLAP DISC","đĩa flap"),
("DIAMOND DISC","đĩa kim cương"),
("DIAMOND CUTTING DISC","đĩa cắt kim cương"),
("ABRASIVE DISC","đĩa mài mòn"),
("DISC","đĩa"),
("DISCS","đĩa"),
("DEPRESSED CENTRE DISC","đĩa cắt lòng chảo"),
("CUT OFF WHEEL","đá cắt"),
("GRINDING WHEEL","đá mài"),
("MOUNTING POINT WHEEL","đá mài mũi"),
("WHEEL","đá mài"),
("WHEELS","đá mài"),
("FLAP WHEEL","quay mài flap"),
("FLAP","flap"),
("BACKING PAD","đế chà chống ma sát"),
("SANDING BELT","dây nhám băng"),
("SANDING DISC","đĩa nhám"),
("ABRASIVE BELT","dây nhám"),
("NONWOVEN ABRASIVE","sợi mài không dệt"),
("FOAM POLISHING PAD","đệm đánh bóng mút"),
("WOOL","len"),
("HOLE SAW","mũi khoan lỗ tròn"),
("DIAMOND CORE BIT","mũi khoan lõi kim cương"),
("CORE BIT","mũi khoan lõi"),
("STEP DRILL BIT","mũi khoan bậc thang"),
("WOOD DRILL BIT","mũi khoan gỗ"),
("MASONRY DRILL BIT","mũi khoan bê tông"),
("CONCRETE DRILL BIT","mũi khoan bê tông"),
("GLASS DRILL BIT","mũi khoan kính"),
("DRILL BIT SET","bộ mũi khoan"),
("DRILL BITS","mũi khoan"),
("DRILL BIT","mũi khoan"),
("SDS PLUS","SDS Plus"),
("SDS MAX","SDS Max"),
("SDS","SDS"),
("HSS","HSS"),
("TCT","TCT"),
("FORSTNER BIT","mũi khoan Forstner"),
("BRAD POINT DRILL BIT","mũi khoan gỗ mũi nhọn"),
("AUGER BIT","mũi khoan xoắn gỗ"),
("SCREW ADAPTER","đầu chuyển vít"),
("TURNING SCREW ADAPTER","đầu chuyển vít xoay"),
("SCREW EXTRACTOR SET","bộ dụng cụ tháo vít đứt"),
("TIE","buộc"),
# hóa chất - keo
("SILICONE SEALANT","keo silicone"),
("ACETIC SILICONE","silicone acetic"),
("ADHESIVE","keo dán"),
("GLUE","keo"),
("GLUE TRAP","bẫy keo"),
("MELT GLUE STICK","cục keo nóng"),
("SEALANT","keo trét"),
("GROUT","keo chít mạch"),
("TAPE","băng keo"),
("MASKING TAPE","băng keo giấy"),
("DOUBLE SIDED TAPE","băng keo hai mặt"),
("PACKING TAPE","băng keo đóng gói"),
("BOPP TAPE","băng keo BOPP"),
("TACK CLOTH","khăn lau dính bụi"),
("PAINT BRUSH","cọ sơn"),
("PAINT ROLLER","con lăn sơn"),
("PAINT","sơn"),
("THINNER","dung môi"),
("SPRAY PAINT","sơn xịt"),
# nhà cửa - khác
("HINGE","bản lề"),
("SOFT CLOSE HINGE","bản lề giảm chấn"),
("NORMAL HINGE","bản lề thường"),
("165 DEGREE SOFT CLOSE HINGE","bản lề giảm chấn 165 độ"),
("165 DEGREE NORMAL HINGE","bản lề thường 165 độ"),
("PADLOCK","ổ khóa"),
("DEADBOLT","khóa then trụ"),
("DOOR STOP","chặn cửa"),
("HOOK","móc treo"),
("MAGNETIC HOOK","móc nam châm"),
("SCALE","cân"),
("THERMOMETER","nhiệt kế"),
("SWITCH","công tắc"),
("OUTLET","ổ cắm"),
("CORD","dây điện"),
("BULB","bóng đèn"),
("TUBE","ống"),
("FUNNEL","phễu"),
("CANISTER","can"),
("BOTTLE","chai"),
("SPRAY BOTTLE","chai xịt"),
("TRIGGER SPRAYER","vòi xịt bóp"),
("ASHTRAY","gạt tàn thuốc"),
("KEYCHAIN","móc khóa"),
("UMBRELLA","ô dù"),
("FLAG","cờ"),
("TENT","lều"),
("NOTE BOOK","sổ tay"),
("BOOK","sách"),
("BROCHURE","brochure giới thiệu"),
("CATALOGUE","catalogue"),
("BILLBOARD","biển quảng cáo"),
("LAMPBOX","hộp đèn quảng cáo"),
("DISPLAY STAND","kệ trưng bày"),
("DISPLAY","trưng bày"),
("STAND","giá đỡ"),
("SHELF","kệ"),
("PRICE TAG","tem giá"),
("LETTER FIGURE","chữ số trang trí"),
("MAGIC TAPE","băng keo trong"),
("VELCRO","băng dính dính velcro"),
("TWEEZER","nhíp"),
("PEN","bút"),
("PENCIL","bút chì"),
("CHALK LINE","dây mực đánh dấu"),
("RULER","thước kẻ"),
("MAGNIFIER","kính lúp"),
("DETECTOR","máy dò"),
("LOCATOR","máy định vị"),
("SENSOR","cảm biến"),
("INSTRUMENT","dụng cụ"),
("TRIPOD","chân máy"),
# máy khác
("AIR COOLED DIESEL GENERATOR","máy phát diesel làm mát bằng gió"),
("DIESEL","diesel"),
("PETROL","xăng"),
("GASOLINE","chạy xăng"),
("SUBMERSIBLE PUMP","máy bơm chìm"),
("CENTRIFUGAL PUMP","máy bơm ly tâm"),
("SELF PRIMING PUMP","máy bơm tự mồi"),
("SURFACE PUMP","máy bơm đặt khô"),
("JET PUMP","máy bơm jet"),
("PUMP","máy bơm"),
("SEWAGE","thoát nước thải"),
("WELL","giếng"),
("RAMMER","máy đầm"),
("POKER","gầu rung"),
("TROWEL","bay xây"),
("PU TROWEL","bay PU"),
("NOTCHED TROWEL","bay răng"),
("FLOAT","bay lá masatô"),
("BRICKLAYING TROWEL","bay xây gạch"),
("PLASTERING TROWEL","bay trát"),
("SKIMMING FLOAT","bay lá san nền"),
("LEVELING","san phẳng"),
("GROUT FLOAT","bay chít mạch"),
("SPONGE FLOAT","bay mút"),
("CHALK","phấn"),
("WALL","tường"),
("CEILING","trần nhà"),
("ROOFING","lợp mái"),
("FLOOR","sàn"),
("DECK","sàn gỗ"),
("TILE CUTTER","máy cắt gạch"),
("TILE","gạch"),
("MARBLE","đá marble"),
("GRANITE","đá granite"),
("WALL CHASER","máy rãnh tường"),
("CHIPPER","máy đục phá"),
("CHIPPING","đục"),
("MIXER","máy trộn"),
("STIRRER","máy khuấy"),
("PAINT MIXER","máy khuấy sơn"),
("EXTRACTOR","máy hút"),
("COLLECTOR","bộ thu"),
("DUST COLLECTOR","bộ thu bụi"),
("AIR FILTER","lọc khí"),
("FILTER","lọc"),
("REGULATOR","van điều áp"),
("LUBRICATOR","bộ bôi trơn"),
("AIR NIBBLER","kéo cắt tôn khí"),
("AIR RATCHET","cờ lè ráy khí"),
("AIR HAMMER","búa khí nén"),
("AIR NEEDLE SCALER","máy gõ mũi kim khí nén"),
("AIR SANDER","máy chà nhám khí"),
("AIR POLISHER","máy đánh bóng khí"),
("AIR DUSTER","súng xịt khí"),
("BLOW GUN","súng thổi hơi"),
("INFLATING GUN","súng bơm hơi"),
("TYRE INFLATOR","máy bơm lốp"),
("SNAP","bẻ"),
("BLADE","lưỡi"),
("BLADES","lưỡi"),
# tính từ - trạng thái
("HEAVY DUTY","siêu bền"),
("HEAVY","nặng"),
("INDUSTRIAL","Công nghiệp"),
("INDSUTRIAL","Công nghiệp"),
("PREMIUM LINE","Dòng cao cấp"),
("PREMIUM","Cao cấp"),
("PROFESSIONAL","chuyên nghiệp"),
("COMMERCIAL","thương mại"),
("MULTIFUNCTIONAL","đa năng"),
("MULTIPURPOSE","đa năng"),
("MULTI PURPOSE","đa năng"),
("MULTI FUNCTION","đa chức năng"),
("MULTI","đa"),
("PURPOSE","năng"),
("QUICK RELEASE","tháo nhanh"),
("AUTOMATIC","tự động"),
("SELF LOCKING","tự khóa"),
("SELF","tự"),
("LOCKING","khóa"),
("REVERSIBLE","đảo chiều"),
("VARIABLE SPEED","chỉnh tốc"),
("SPEED","tốc độ"),
("FOLDABLE","gập gọn"),
("FOLDING","gập"),
("TELESCOPIC","rút dài"),
("TELESCOPING","rút dài"),
("EXPANDABLE","co giãn"),
("SILENT TYPE","loại êm"),
("SILENT","êm"),
("WET AND DRY","khô và ướt"),
("WET","ướt"),
("DRY","khô"),
("NON SPARKING","chống tia lửa"),
("NON-SPARKING","chống tia lửa"),
("NON SPARK","chống tia lửa"),
("NON WOVEN","không dệt"),
("INSULATED","cách điện"),
("INSULATING","cách điện"),
("INTERCHANGEABLE","đổi đầu được"),
("CHANGEABLE","đổi mũi"),
("REMOVABLE","tháo rời"),
("DETACHABLE","tháo rời"),
("ADJUSTABLE","điều chỉnh"),
("FIXED","cố định"),
("SWIVEL","xoay"),
("REVOLVING","quay"),
("ROTATING","quay"),
("SLIDING","trượt"),
("FLEXIBLE","mềm"),
("RIGID","cứng"),
("STRAIGHT","thẳng"),
("BENT","cong"),
("OFFSET","lệch"),
("FLAT","dẹt"),
("ROUND","tròn"),
("OVAL","oval"),
("CYLINDRICAL","trụ"),
("HOLLOW","rỗng"),
("SOLID","đặc"),
("DOUBLE","kép"),
("SINGLE","đơn"),
("DUAL","kép"),
("TWIN","song"),
("THREE","ba"),
("FOUR","bốn"),
("FIVE","năm"),
("TWO","hai"),
("ONE","một"),
("PIECE","chi tiết"),
("MAGNETIC","nam châm"),
("DIGITAL","điện tử"),
("ELECTRONIC","điện tử"),
("ELECTRIC","điện"),
("ELECTRICAL","điện"),
("PORTABLE","di động"),
("COMPACT","nhỏ gọn"),
("ULTRA COMPACT","siêu nhỏ gọn"),
("ULTRATHIN","siêu mỏng"),
("PRECISION","chính xác"),
("EXTRA LONG","siêu dài"),
("EXTRA","siêu"),
("LONG","dài"),
("SHORT","ngắn"),
("DEEP","sâu"),
("MINI","mini"),
("MAX","tối đa"),
("BIG","to"),
("SMALL","nhỏ"),
("SUPER","siêu"),
("HELD","cầm tay"),
("OPEN","mở"),
("CLOSE","đóng chậm"),
("NORMAL","thường"),
("QUICK","nhanh"),
("FAST","nhanh"),
("SLOW","chậm"),
("HOT","nóng"),
("COLD","lạnh"),
("REPAIR","sửa chữa"),
("SERVICE","bảo dưỡng"),
("INSTALLATION","lắp đặt"),
("REMOVAL","tháo lắp"),
("REMOVE","tháo"),
("RETRACTING","thu vào"),
("RELEASE","nhả"),
("CONTROL","điều khiển"),
("ADJUSTMENT","điều chỉnh"),
("BALANCING","cân bằng"),
("BALANCER","máy cân bằng"),
("ALIGNER","máy căn chỉnh"),
("CHANGER","máy thay"),
("CHANGER","máy thay"),
("SUPPORT","giá đỡ"),
("PROTECTIVE","bảo vệ"),
("RESISTANCE","chống"),
("REUSABLE","dùng lại"),
("CLEAR","trong"),
("RED","đỏ"),
("WHITE","trắng"),
("BLACK","đen"),
("BROWN","nâu"),
("COLOR","màu"),
("MEDIUM","vừa"),
("HEAVY","nặng"),
("LIGHT","nhẹ"),
("LOW","thấp"),
("HIGH","cao"),
("TOP","trên"),
("DOWN","xuống"),
("BACK","sau"),
("FRONT","trước"),
("SIDE","bên"),
("CORNER","góc"),
("ROW","hàng"),
("SET OF","bộ"),
("SETS","bộ"),
("SET","bộ"),
("KIT","bộ"),
("ASSORTMENT","tuyển tập"),
("PARTS","phụ tùng"),
("ACCESSORIES","phụ kiện"),
("ACCESSORY","phụ kiện"),
("EQUIPMENT","thiết bị"),
("MACHINE","máy"),
("SYSTEM","hệ thống"),
("TYPE","loại"),
("LINE","dòng"),
("PATTERN","hoa văn"),
("PATTEN","hoa văn"),
("SHAPE","hình dạng"),
("SIZE","cỡ"),
("METRIC","metric"),
("BRITISH","chuẩn Anh"),
("SWEDISH","kiểu Thụy Điển"),
("FRENCH","kiểu Pháp"),
("GERMAN","chuẩn Đức"),
("AMERICAN","chuẩn Mỹ"),
# vật liệu
("STAINLESS STEEL","inox"),
("CHROME VANADIUM","crom vanadium"),
("CARBON STEEL","thép carbon"),
("STEEL","thép"),
("ALUMINIUM","nhôm"),
("ALUMINUM","nhôm"),
("PLASTIC","nhựa"),
("RUBBER","cao su"),
("BRASS","đồng thau"),
("COPPER","đồng"),
("WOODEN","gỗ"),
("WOOD","gỗ"),
("FIBERGLASS","sợi thủy tinh"),
("FIBRE GLASS","sợi thủy tinh"),
("FIBER","sợi"),
("FIBRE","sợi"),
("NYLON","nylon"),
("TITANIUM","titanium"),
("CARBIDE","hợp kim cứng"),
("DIAMOND","kim cương"),
("ZIRCONIA","zirconia"),
("POLYURETHANE","polyurethane"),
("POLYMER","polymer"),
("LEATHER","da"),
("KNITTED","đan"),
("WOVEN","dệt"),
("GALVANIZED","mạ kẽm"),
("ELECTRIPLATING","mạ điện"),
("BRAZED","hàn brazed"),
("CAST","đúc"),
("FORGED","rèn"),
("TIN","thiếc"),
("IRON","sắt"),
("COPPER","đồng"),
("SILICONE","silicone"),
("FOAM","mút"),
("SPONGE","bọt biển"),
("CLOTH","khăn"),
("MESH","lưới"),
("NET","lưới"),
("PTFE","PTFE"),
("PE","PE"),
("PP","PP"),
("PU","PU"),
("PVC","PVC"),
("MS","MS"),
# động cơ - thông số
("ELECTRIC MOTOR","motor điện"),
("ENGINE","động cơ"),
("MOTOR","motor"),
("GEAR","bánh răng"),
("GEARBOX","hộp số"),
("PISTON","piston"),
("CYLINDER","xy lanh"),
("BUSHING","bushing"),
("BUSH","bush"),
("BEARING","vòng bi"),
("SPRING","lò xo"),
("VALVE","van"),
("SEAL","gioăng"),
("GASKET","gioăng"),
("BELT","dây curoa"),
("CHAIN","xích"),
("SHEAVE","ròng rọc"),
("PULLEY","ròng rọc"),
("BOLT","bu lông"),
("NUT","đai ốc"),
("WASHER","vòng đệm"),
("SCREW","vít"),
("RIVET","đinh tán"),
("STAPLES","ghim"),
("NAIL","đinh"),
("PIN","chốt"),
("CLIP","kẹp"),
("CLIPS","kẹp"),
("THREAD","ren"),
("THREADING","tiện ren"),
("TAPPING","taró"),
("TAP AND DIE SET","bộ tarô ta rô ren"),
("TAP","ta rô"),
("DIE","ta rô úp"),
("DIES","ta rô úp"),
("DRILLING","khoan"),
("GRINDING","mài"),
("CUTTING","cắt"),
("CUT","cắt"),
("CUTTER","kìm cắt"),
("CUTTERS","kìm cắt"),
("FINISHING","hoàn thiện"),
("POLISHING","đánh bóng"),
("SANDING","chà nhám"),
("SHARPENING","mài sắc"),
("TREPANNING","khoan lõi"),
("FLARING","loe ống"),
("SWAGING","thắt ống"),
("BENDING","uốn"),
("STRAIGHTENING","nắn thẳng"),
# động từ - danh từ chung
("WITH","có"),
("WITHOUT","không có"),
("AND","và"),
("FOR","cho"),
("IN","trong"),
("ON","trên"),
("OF","của"),
("OFF","bẻ"),
("PLUS","Plus"),
("TYPE","loại"),
("STYLE","kiểu"),
("MODEL","mẫu"),
("NO.","số"),
("DEGREE","độ"),
("DEG","độ"),
("INCH","inch"),
("SQ","vuông"),
# thương hiệu - riêng
("WOKIN","WOKIN"),
("GP20V","GP20V"),
]
# sort: dài trước, ngắn sau
TERMS = sorted(T, key=lambda kv: -len(kv[0]))

SPEC_MAP = {
    'INDUSTRIAL': 'Công nghiệp', 'Industrial': 'Công nghiệp',
    'INDSUTRIAL': 'Công nghiệp',
    'PREMIUM': 'Cao cấp', 'Premium': 'Cao cấp',
    'PREMIUM LINE': 'Dòng cao cấp', 'Premium Line': 'Dòng cao cấp',
    'HEAVY DUTY': 'Siêu bền', 'Heavy Duty': 'Siêu bền', 'HEAVY-DUTY': 'Siêu bền',
    'PROFESSIONAL': 'Chuyên nghiệp', 'Professional': 'Chuyên nghiệp',
    'SPECIALLY FOR 110-120V MARKET': 'Dùng cho điện 110–120V',
    'SPECIALLY FOR 220-240V MARKET': 'Dùng cho điện 220–240V',
}

QTY_RE = re.compile(r'^(\d+)\s*(?:PCS|Pcs|pcs|PC|PC\.|PCS\.)\b\s*')
SPEC_RE = re.compile(r'\(([^()]*)\)')

def translate_chunk(s):
    # chuẩn hoá hyphen giữa các chữ thành khoảng trắng để match cụm
    s = re.sub(r'(?<=[A-Za-z])-(?=[A-Za-z])', ' ', s)
    s = re.sub(r'(?<=[A-Za-z])/(?![\d])', ' ', s)  # chữ/chữ -> space, giữ số/số
    for en, vi in TERMS:
        pat = r'(?<![A-Za-z0-9])' + re.escape(en).replace('\\ ', '\\s+') + r'(?![A-Za-z0-9])'
        s = re.sub(pat, vi, s, flags=re.I)
    return re.sub(r'\s{2,}', ' ', s).strip()

def translate_name(raw):
    name = H.unescape(raw).replace('\u2033', '"').strip()
    # tách ngoặc
    specs_raw = SPEC_RE.findall(name)
    core = SPEC_RE.sub(' ', name).strip()
    # số lượng đầu chuỗi
    qty = None
    mq = QTY_RE.match(core)
    if mq:
        qty = f'{mq.group(1)} chi tiết'
        core = core[mq.end():].strip()
    # dịch phần chính
    core = translate_chunk(core)
    # dịch ngoặc
    vi_specs = []
    for sp in specs_raw:
        sp = sp.strip()
        sp_u = sp.upper().replace('-', ' ')
        if sp_u in SPEC_MAP:
            vi_specs.append(SPEC_MAP[sp_u])
        elif re.fullmatch(r'[0-9\s./"\'°\-–—+.A-Za-z]+', sp):
            vi_specs.append(sp)
        else:
            vi_specs.append(translate_chunk(sp))
    # ghép: core + qty cuối + specs
    out = core
    if qty:
        out = f'{out} {qty}' if out else qty
    for sp in vi_specs:
        out += f' ({sp})'
    out = re.sub(r'\s{2,}', ' ', out).strip()
    return out[:1].upper() + out[1:] if out else out

def vi_slug(s):
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    s = s.replace('đ','d').replace('Đ','D')
    s = re.sub(r'[^a-zA-Z0-9\s-]','', s)
    s = re.sub(r'[\s_]+','-', s.strip().lower())
    return re.sub(r'-{2,}','-', s).strip('-')

def main():
    prods = json.load(open(os.path.join(DATA,'products.json')))
    final=[]; seen={}
    for p in prods:
        vi = translate_name(p['name'])
        sv = vi_slug(vi) or 'san-pham'
        if sv in seen:
            seen[sv]+=1
            sv=f'{sv}-{p["sku"]}'
        else:
            seen[sv]=1
        final.append({'id':p['id'],'sku':p['sku'],'name_en':p['name'],'name_vi':vi,'slug_vi':sv})
    json.dump(final, open(os.path.join(DATA,'products_vi.json'),'w'), ensure_ascii=False, indent=1)
    # báo cáo chất lượng: tìm tên còn chứa chuỗi HOA >= 3 ký tự chưa dịch
    allow={'SDS','LED','HSS','TCT','PVC','PU','PP','PE','HP','DC','AC','GA','MS','PSI','ML','LB','LBS','KG','FT','OZ','SQ','MMA','MIG','VDE','GDI','SPT','THWN','BOPP','HVLP','CR-V','CC'}
    bad=[]
    for f in final:
        for tok in re.findall(r'[A-Za-z]{3,}', f['name_vi']):
            if tok.isupper() and tok not in allow and not re.fullmatch(r'WOKIN|GP20V', tok):
                bad.append((f['sku'], f['name_en'], f['name_vi'], tok))
                break
    print('TOTAL:', len(final))
    print('CON CHU HOA CHUA DICH:', len(bad))
    for b in bad[:25]:
        print(' !', b[0], '|', b[1], '=>', b[2], '| residue:', b[3])
    import random
    random.seed(5)
    print('\n--- MAU NGAU NHIEN ---')
    for r in random.sample(final, 15):
        print(f'{r["name_en"]}\n   -> {r["name_vi"]}   [{r["slug_vi"]}]')

if __name__ == '__main__':
    main()
